apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "metaman.fullname" . }}-sync-template
spec:
  arguments:
    parameters:
      - name: db
        value: database
      - name: source_metastore
        value: hive
      - name: target_metastore
        value: glue
      - name: tables
        value: table1,table2
    templates:
      - name: metaman-sync-template
        inputs:
          parameters:
            - name: db
            - name: source_metastore
            - name: target_metastore
            - name: tables
        volumes:
          - name: config-volume
            configMap:
              name: {{ .Release.Name }}-configmap
        container:
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          volumeMounts:
            - mountPath: /config
              name: config-volume
          command: [ metaman ]
          args:
            - >-
              sync -c /config/config.yml -d {{printf "{{inputs.parameters.db}} -s {{inputs.parameters.source_metastore}} -t {{inputs.parameters.target_metastore}} --tables {{inputs.parameters.tables}}"}}
          resources:
            {{.Values.resources}}
