apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name:  {{ include "metaman.drop.fullname" . }}-sync-template
spec:
  arguments:
    parameters:
      - name: db
        value: database
      - name: source_metastore
        value: hive
      - name: target_metastore
        value: glue
      - name: tables
        value: table1,table2
    templates:
      - name: metaman-dop-template
        inputs:
          parameters:
            - name: db
            - name: redis-sentinel-port
            - name: redis-db
        container:
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
            args: [ "/config/config.yml" ]
            volumeMounts:
              - mountPath: /config
                name: config-volume
          command: [ metaman ]
          args:
            - >-
              sync -c /config/config.yml -d {{inputs.parameters.db}} -s {{inputs.parameters.source_metastore}} -t {{inputs.parameters.target_metastore}} --tables {{inputs.parameters.tables}}
          resources:
            {{- with .Values.resources}}
