apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
data:
  config.yml: |
    {{- with .Values.config }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_key }}